steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'chat-front'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chat-front-alpha', '.']
images:
  - 'gcr.io/$PROJECT_ID/chat-front-alpha'
options:
  logging: CLOUD_LOGGING_ONLY